apiVersion: v1
kind: ServiceAccount
metadata:
  name: layersentry-production-ui
  namespace: layersentry-system
  labels:
    app.kubernetes.io/name: layersentry-production-ui
    app.kubernetes.io/part-of: layersentry
automountServiceAccountToken: false
