// Code generated by values-gen. DO NOT EDIT.
// +kubebuilder:object:generate=true
// +groupName=apps.cozystack.io
// +versionName=v1alpha1
package vmnetwork

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +kubebuilder:object:root=true
type Config struct {
	v1.TypeMeta   `json:",inline"`
	v1.ObjectMeta `json:"metadata,omitempty"`
	Spec          ConfigSpec `json:"spec,omitempty"`
}

// +kubebuilder:validation:XValidation:rule="(self.fabricRef == '' && self.fabricNetwork == '') || (self.fabricRef != '' && self.fabricNetwork != '')",message="fabricRef and fabricNetwork must be set together"
type ConfigSpec struct {
	// Linux bridge on KubeVirt-capable nodes that carries this external VM network.
	Bridge string `json:"bridge"`
	// 802.1Q VLAN ID. Use 0 for an untagged/native network.
	// +kubebuilder:default:=0
	// +kubebuilder:validation:Minimum=0
	// +kubebuilder:validation:Maximum=4094
	Vlan int64 `json:"vlan"`
	// Interface MTU. Use 0 to inherit/default; otherwise use 576-9216.
	// +kubebuilder:default:=0
	// +kubebuilder:validation:Minimum=0
	// +kubebuilder:validation:Maximum=9216
	// +kubebuilder:validation:XValidation:rule="self == 0 || self >= 576",message="mtu must be 0 or between 576 and 9216"
	Mtu int64 `json:"mtu"`
	// Optional cluster NetworkFabric backing this tenant network. Set together with fabricNetwork for verified node placement.
	// +kubebuilder:default:=""
	FabricRef string `json:"fabricRef"`
	// Network name inside fabricRef. Set together with fabricRef.
	// +kubebuilder:default:=""
	FabricNetwork string `json:"fabricNetwork"`
	// Human-readable description of the physical VM network.
	// +kubebuilder:default:=""
	Description string `json:"description"`
	// Enable promiscuous mode on the bridge CNI interface.
	// +kubebuilder:default:=false
	PromiscMode bool `json:"promiscMode"`
	// Enable MAC spoof checking when supported by the bridge CNI.
	// +kubebuilder:default:=false
	Macspoofchk bool `json:"macspoofchk"`
	// Enable bridge hairpin mode for this network.
	// +kubebuilder:default:=false
	HairpinMode bool `json:"hairpinMode"`
}
