// Code generated by values-gen. DO NOT EDIT.
// +kubebuilder:object:generate=true
// +groupName=apps.cozystack.io
// +versionName=v1alpha1
package vmtemplate

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +kubebuilder:object:root=true
type Config struct {
	v1.TypeMeta   `json:",inline"`
	v1.ObjectMeta `json:"metadata,omitempty"`
	Spec          ConfigSpec `json:"spec,omitempty"`
}

type ConfigSpec struct {
	// Tenant-local Cozystack VMInstance to capture. The source must be halted and have no active VMI.
	SourceVM string `json:"sourceVM"`
	// Copy keeps the source VMInstance. Convert retires it only after the template is verified Ready and the source UID/generation still match preflight.
	// +kubebuilder:default:="Copy"
	// +kubebuilder:validation:Enum=Copy;Convert
	Mode string `json:"mode"`
	// Exclude installer, VirtIO-driver, rescue and other optical VMDisk attachments from the reusable template.
	// +kubebuilder:default:=true
	ExcludeOpticalMedia bool `json:"excludeOpticalMedia"`
	// Optional human-readable template description.
	// +kubebuilder:default:=""
	// +kubebuilder:validation:MaxLength=512
	Description string `json:"description"`
}
