// Code generated by values-gen. DO NOT EDIT.
// +kubebuilder:object:generate=true
// +groupName=apps.cozystack.io
// +versionName=v1alpha1
package vmdisk

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +kubebuilder:object:root=true
type Config struct {
	v1.TypeMeta   `json:",inline"`
	v1.ObjectMeta `json:"metadata,omitempty"`
	Spec          ConfigSpec `json:"spec,omitempty"`
}

type ConfigSpec struct {
	// The source used to create the disk or optical-media object.
	// +kubebuilder:default:={}
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="source is immutable"
	Source Source `json:"source"`
	// Defines if this tenant object is optical media. Platform source.iso entries are automatically optical even when this value is false.
	// +kubebuilder:default:=false
	Optical bool `json:"optical"`
	// Optional human-readable media name shown in catalog metadata.
	// +kubebuilder:default:=""
	DisplayName string `json:"displayName"`
	// Optional optical-media category: installer, drivers, rescue, appliance, or custom.
	// +kubebuilder:default:=""
	MediaCategory string `json:"mediaCategory"`
	// Optional operating-system family metadata, for example Linux or Windows.
	// +kubebuilder:default:=""
	OsFamily string `json:"osFamily"`
	// Optional operating-system/distribution name metadata.
	// +kubebuilder:default:=""
	OsName string `json:"osName"`
	// Optional operating-system version metadata.
	// +kubebuilder:default:=""
	OsVersion string `json:"osVersion"`
	// Optional CPU architecture metadata, for example amd64 or arm64.
	// +kubebuilder:default:=""
	Architecture string `json:"architecture"`
	// Optional human-readable disk/media description.
	// +kubebuilder:default:=""
	Description string `json:"description"`
	// The size of the disk/media object allocated for the virtual machine.
	// +kubebuilder:default:="5Gi"
	Storage resource.Quantity `json:"storage"`
	// StorageClass used to store the data.
	// +kubebuilder:default:="replicated"
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="storageClass is immutable"
	StorageClass string `json:"storageClass"`
}

type Source struct {
	// Clone an existing vm-disk.
	Disk *SourceDisk `json:"disk,omitempty"`
	// Download content from an HTTP source. Set optical=true when importing ISO media.
	Http *SourceHTTP `json:"http,omitempty"`
	// Use a golden disk image from the platform collection.
	Image *SourceImage `json:"image,omitempty"`
	// Clone an ISO from the platform ISO Library. This source is always treated as optical media.
	Iso *SourceISO `json:"iso,omitempty"`
	// Upload local content. Set optical=true when uploading ISO media.
	Upload *SourceUpload `json:"upload,omitempty"`
}

type SourceDisk struct {
	// Name of the vm-disk to clone.
	Name string `json:"name"`
}

type SourceHTTP struct {
	// URL to download the content from.
	Url string `json:"url"`
}

type SourceISO struct {
	// Name of the platform ISO to use.
	Name string `json:"name"`
}

type SourceImage struct {
	// Name of the image to use.
	Name string `json:"name"`
}

type SourceUpload struct {
}
