apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: network-fabric-controller
  labels:
    app.kubernetes.io/name: network-fabric-controller
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: network-fabric-controller
