#!/bin/sh
set -eu

PROFILES="initramfs kernel iso installer nocloud metal"
EMBEDDED_MACHINE_CONFIG=${EMBEDDED_MACHINE_CONFIG:-layersentry-hci-machine-config.yaml}
LAYERSENTRY_ISCSI_TARGET_TARBALL=${LAYERSENTRY_ISCSI_TARGET_TARBALL:-/extensions/layersentry-iscsi-target.tar}
LAYERSENTRY_NFS_SERVER_TARBALL=${LAYERSENTRY_NFS_SERVER_TARBALL:-/extensions/layersentry-nfs-server.tar}
LAYERSENTRY_HCI_TOOLS_TARBALL=${LAYERSENTRY_HCI_TOOLS_TARBALL:-/extensions/layersentry-hci-tools.tar}

# Firmware/microcode and userspace-only extensions remain the exact official
# v1.13.6 artifacts and are resolved to immutable digests from Sidero's catalog.
OFFICIAL_EXTENSIONS="
amd-ucode
intel-ice-firmware
intel-ucode
qlogic-firmware
iscsi-tools
multipath-tools
nfs-utils
nfsrahead
nvme-cli
lldpd
trident-iscsi-tools
util-linux-tools
nvidia-container-toolkit-production
"

# These extensions carry kernel modules. They are rebuilt from the exact
# Sidero v1.13.6 extension source against LayerSentry's custom signed kernel.
# ZFS is additionally sanitized so it never force-imports all visible pools.
KERNEL_EXTENSIONS="
amdgpu
bnx2-bnx2x
i915
drbd
zfs
nfsd
nvidia-open-gpu-kernel-modules-production
nvidia-gdrdrv-device
"

if [ -n "${1:-}" ]; then
  TALOS_VERSION=$1
else
  TALOS_VERSION=$(docker image ls --format '{{.Tag}}' ghcr.io/siderolabs/imager | grep -v '<none>' | sort -V | tail -1)
fi

if [ -z "$TALOS_VERSION" ]; then
  echo "ERROR: Talos version could not be resolved" >&2
  exit 1
fi

BASE_INSTALLER_IMAGE=${BASE_INSTALLER_IMAGE:-ghcr.io/siderolabs/installer:${TALOS_VERSION}}
CATALOG_IMAGE="ghcr.io/siderolabs/extensions:${TALOS_VERSION}"
CATALOG_TMP=$(mktemp)
trap 'rm -f "$CATALOG_TMP"' EXIT INT TERM

docker run --rm --entrypoint /bin/sh "$CATALOG_IMAGE" -c 'cat /image-digests' > "$CATALOG_TMP"

resolve_extension() {
  name=$1
  ref=$(awk -v n="/$name:" 'index($0,n){print; exit}' "$CATALOG_TMP")
  if [ -z "$ref" ]; then
    echo "ERROR: extension '$name' is not present in ${CATALOG_IMAGE}" >&2
    exit 1
  fi
  printf '%s\n' "$ref"
}

emit_extensions() {
  for extension in $OFFICIAL_EXTENSIONS; do
    ref=$(resolve_extension "$extension")
    printf '    - imageRef: %s\n' "$ref"
  done

  for extension in $KERNEL_EXTENSIONS; do
    printf '    - tarballPath: /extensions/layersentry-%s.tar\n' "$extension"
  done

  printf '    - tarballPath: %s\n' "$LAYERSENTRY_ISCSI_TARGET_TARBALL"
  printf '    - tarballPath: %s\n' "$LAYERSENTRY_NFS_SERVER_TARBALL"
  printf '    - tarballPath: %s\n' "$LAYERSENTRY_HCI_TOOLS_TARBALL"
}

for PROFILE in $PROFILES; do
  OUT="images/talos/profiles/${PROFILE}.yaml"
  {
    cat <<EOF
# this file generated by hack/gen-profiles.sh; do not edit
arch: amd64
platform: metal
secureboot: false
version: ${TALOS_VERSION}
input:
  kernel:
    path: /usr/install/amd64/vmlinuz
  initramfs:
    path: /usr/install/amd64/initramfs.xz
  sdStub:
    path: /usr/install/amd64/systemd-stub.efi
  sdBoot:
    path: /usr/install/amd64/systemd-boot.efi
  baseInstaller:
    imageRef: ${BASE_INSTALLER_IMAGE}
  systemExtensions:
EOF
    emit_extensions

    if [ "$PROFILE" != "kernel" ]; then
      cat <<EOF
customization:
  # Preserve the branch's existing ethX compatibility for now; all destructive
  # storage/network actions must still identify hardware by stable MAC/PCI/WWID.
  extraKernelArgs:
    - net.ifnames=0
  embeddedMachineConfiguration:
EOF
      sed 's/^/    /' "$EMBEDDED_MACHINE_CONFIG"
    fi

    case "$PROFILE" in
      initramfs)
        cat <<EOF
output:
  kind: initramfs
  outFormat: raw
EOF
        ;;
      kernel)
        cat <<EOF
output:
  kind: kernel
  outFormat: raw
EOF
        ;;
      iso)
        cat <<EOF
output:
  kind: iso
  outFormat: raw
EOF
        ;;
      installer)
        cat <<EOF
output:
  kind: installer
  outFormat: raw
EOF
        ;;
      nocloud)
        cat <<EOF
output:
  kind: image
  imageOptions:
    diskSize: 2147483648
    diskFormat: raw
    platform: nocloud
  outFormat: xz
EOF
        ;;
      metal)
        cat <<EOF
output:
  kind: image
  imageOptions:
    diskSize: 2147483648
    diskFormat: raw
  outFormat: xz
EOF
        ;;
      *)
        echo "ERROR: unsupported profile $PROFILE" >&2
        exit 1
        ;;
    esac
  } > "$OUT"
done
