apiVersion: v2
name: cozy-linstor-gateway
version: 0.0.0 # Placeholder, the actual version will be automatically set during the build process
appVersion: "2.3.0"
description: LayerSentry integration package for LINSTOR Gateway
