---
apiVersion: cozystack.io/v1alpha1
kind: PackageSource
metadata:
  name: cozystack.vm-template-application
spec:
  sourceRef:
    kind: OCIRepository
    name: cozystack-packages
    namespace: cozy-system
    path: /
  variants:
    - name: kubevirt
      dependsOn:
        - cozystack.kubevirt
        - cozystack.cozystack-engine
      components:
        - name: vm-template-crd
          path: system/vm-template-crd
          install:
            namespace: cozy-system
            releaseName: vm-template-crd
        - name: vm-template-controller
          path: system/vm-template-controller
          install:
            namespace: cozy-system
            releaseName: vm-template-controller
        - name: vm-template-rd
          path: system/vm-template-rd
          install:
            namespace: cozy-system
            releaseName: vm-template-rd
        - name: vm-template
          path: apps/vm-template
